# Generated by Django 5.2 on 2025-05-03 22:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userachievement',
            options={},
        ),
        migrations.RenameField(
            model_name='userachievement',
            old_name='achieved_at',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='userachievement',
            name='achievement_type',
        ),
        migrations.RemoveField(
            model_name='userachievement',
            name='details',
        ),
        migrations.RemoveField(
            model_name='userachievement',
            name='is_new',
        ),
        migrations.AddField(
            model_name='userachievement',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userachievement',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userachievement',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userachievement',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_achievements', to=settings.AUTH_USER_MODEL),
        ),
    ]
