# Generated by Django 5.2 on 2025-05-06 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_user', '0002_alter_userachievement_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interactionhistory',
            old_name='input_text',
            new_name='username',
        ),
    ]
